### ISSUE TITLE
Annotator and REcommender and Home page AgroPortal "sample text" has been lost in latest release

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#588]
<img width="1000" alt="Capture d’écran 2024-04-22 à 23 11 06" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/a783c77d-9a8d-4f70-b5b1-1a2d15a7ada3">

**Comment by syphax-bouazzouni** [comment]
> I went through the repo's history to find the new sample text but was unable to find it. Do you @syphax-bouazzouni @jonquet by any chance have or remember the sample text that we lost?

Me no, but internet does
```yaml
  annotator:
    index:
      intro: The %{site} Annotator processes text submitted by users, recognizes relevant ontology terms in the text and returns 
          the annotations to the user. Use the interface below to submit sample text to get ontology-based annotations. Hover the mouse pointer on any 
          button to see what it does.
      annotatorplus_html: <em>Check out <a href="%{annotatorplus_href}">AnnotatorPlus</a> beta; a new version of the Annotator with added support for negation, and more!</em>
      fast_context:
        tooltip: "Enable FastContext to detect : if a concept has been negated (affirmed, negated), who experienced the found concept (patient, other), when the annotated concept occurred (recent, historical, hypothetical), and/or if the annotated concept is uncertain (certain, uncertain)."
      sample_text: There has been many recent studies on the use of microbial antagonists to control diseases incited by soilborne and airborne plant pathogenic bacteria
              and fungi, in an attempt to replace existing methods of chemical control and avoid extensive use of fungicides, which often lead to resistance in plant pathogens.
              In agriculture, plant growth-promoting and biocontrol microorganisms have emerged as safe alternatives to chemical pesticides. Streptomyces spp. and their
              metabolites may have great potential as excellent agents for controlling various fungal and bacterial phytopathogens.

  recommender:
    intro: Get recommendations for the most relevant ontologies based on an excerpt from a text or a list of keywords
    sample_keywords: Backpain, White blood cell, Carcinoma, Cavity of stomach, Ductal Carcinoma in Situ, Adjuvant chemotherapy, Axillary lymph node staging, Mastectomy, tamoxifen, serotonin reuptake inhibitors, Invasive Breast Cancer, hormone receptor positive breast cancer, ovarian ablation, premenopausal women, surgical management, biopsy of breast tumor, Fine needle aspiration, entinel lymph node, breast preservation, adjuvant radiation therapy, prechemotherapy, Inflammatory Breast Cancer, ovarian failure, Bone scan, lumpectomy, brain metastases, pericardial effusion, aromatase inhibitor, postmenopausal, Palliative care, Guidelines, Stage IV breast cancer disease, Trastuzumab, Breast MRI examination
    sample_text: There has been many recent studies on the use of microbial antagonists to control diseases incited by soilborne and airborne plant pathogenic bacteria
              and fungi, in an attempt to replace existing methods of chemical control and avoid extensive use of fungicides, which often lead to resistance in plant pathogens.
              In agriculture, plant growth-promoting and biocontrol microorganisms have emerged as safe alternatives to chemical pesticides. Streptomyces spp. and their
              metabolites may have great potential as excellent agents for controlling various fungal and bacterial phytopathogens.

```
